// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CollapseTransition: typeof import('./src/components/transitions/CollapseTransition.vue')['default']
    Empty: typeof import('./src/components/empty.vue')['default']
    FieldAreaPicker: typeof import('./src/components/field-area-picker.vue')['default']
    FieldCalendarPicker: typeof import('./src/components/field-calendar-picker.vue')['default']
    FieldDatetimePicker: typeof import('./src/components/field-datetime-picker.vue')['default']
    FieldPicker: typeof import('./src/components/field-picker.vue')['default']
    FormNavBar: typeof import('./src/components/NavBar/FormNavBar.vue')['default'];
    List: typeof import('./src/components/List/index.vue')['default']
    ListCard: typeof import('./src/components/list-card.vue')['default'];
    Normalempty: typeof import('./src/components/EmptyView/normalempty.vue')['default']
    PersonSelect: typeof import('./src/components/person-select.vue')['default']
    PullRefresh: typeof import('./src/components/PullRefresh/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPerson: typeof import('./src/components/search-person.vue')['default']
    TitleNavBar: typeof import('./src/components/NavBar/TitleNavBar.vue')['default']
    VanCard: typeof import('vant/es')['Card']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VantSearch: typeof import('vant/es')['tSearch']
  }
}

export {}
